server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/users, /api/v1/users/**
      forwarded:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
