server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://user-postgres:5432/users_db
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    import: optional:configserver:http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
